### PR TITLE
Initial event-based culling implementation

### PR DESCRIPTION
**Pull request by noamross**
-  New parameter needed: cull_time (days),
   internally represented as cull_rate (1/days). It
   may be set as farm-specific.
-  Input/output state 5-part: SIRVC, with C being
   culling state, a 0,1,2 value
-  Updated tests
-  Updated one experiment (01-growth-initial) to
   work with new inputs/outputs

### CODE REVIEW

**Comment by noamross** [comment]
First crack at rate-based culling here.  Changes summarized above.  Please give a go at testing this version.  You can update previous experiments with the new parameter/initial state and push to this branch.  Once we're sure they're all working, updated any helper functions, and have run an experiment testing that the culling behaves as expected, we can merge this in.

@kateroyce If you haven't worked with git branches yet, you can check out this branch and work with it by going to the drop-down menu in the corner of RStudio's git pane and selecting `REMOTE: ORIGIN/cull-event`.  It will update your files (be sure to have commited any local changes first), and you can work on this branch, commit, push to it, and switch back to `master` as you need.

**Comment by noamross** [comment]
I realize this doesn't yet implement any network changes when a farm is culled.  We decided that a culled farm should no longer have chickens imported to it, and those chickens should be distributed to other farms, correct?

**Comment by calebasaraba** [comment]
Yes, I think that's right -- my notes from the meeting say:

- kill all chickens
- update to culled state
- set connections to culled farm to zero, re-weight network for connected farms

**Comment by noamross** [comment]
OK, implemented.  It would be useful to have some tests for this culling behavior in general:

- ~~In a run with expected culling, culled farms remain culled (C=2), with no chickens (S+I+R = 0), for the duration of simulation.~~
- ~~Farm culling state only increases and is never other than 0,1, or 2.~~
- For runs with no background mortality, reporting and culling occur after at least `I_crit` mortalities.
  - _Impossible to discriminate between leaving/dying_
- ~~Also, no chickens "disappear" -> only infected chickens die.  This will ensure I did the network re-normalization properly and emigrating chickens aren't going into the ether.~~

**Comment by noamross** [comment]
Excellent work on this, @calebasaraba.  I like the test graphs.  I suppose the reason that the mean time-to-cull is always a bit above the parameterized value is due to the output bins, but I'll have to think about that.  

Also, I'm still getting this:

```
==> devtools::test()

Loading metaflu
Loading required package: testthat
Testing metaflu
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Culling: .1.
Reproducibility: ..........

Failed -------------------------------------------------------------------------
1. Failure: Culled farms remain empty (@test_culling.R#66) ---------------------
all(truths) isn't true.
```

Also, for some reason when I run the simulations in the culling test file, my sims are hanging.  Any thoughts? We can discuss this at our check-in on Weds.

**Comment by calebasaraba** [comment]
Interesting, I'll look into that test -- they were all working earlier, but perhaps there is something subtle happening with the merge.

**Comment by calebasaraba** [comment]
I can't seem to replicate the failed test or the hanging behavior, we can review in our check-in meeting!

**Comment by calebasaraba** [comment]
I ran `devtools::test()` and `test_culling.R` on aegypti ten times and they each worked, except for one `test_culling.R` run, which appeared to hang -- but I'd also lost connection to aegypti... so it was unclear if it was truly hanging.

**Pull request merged**
